---
cjones      :
    comment : "Craig Jones"
    keys    :
      - key : "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDkmh8kI6776c2pEtD8BHyVgk4Fl5MnQlnwXftlwJ9h0bq04uqTgoubQDY/BTr4YQuoxgYCw2y/n4lYqeatDDYlafp11nBSZNZsow6/dgQOcFhkboATQnb85OUfjWue+JRYqB17g1h41x8PIojr2mfovS+fVYOn1n7leHHJtAcGXrIVIwXHs0290/CjmwPFIPYaL/63SbqpOnWi8C+U+t+exQrov4YR4odOX8WNdep5TuYCd27tlXeqkGaAL8TnUIeyVGWIFqQUltNJpa7owTkaIO+6Jp97CqviLs3S6wdBfv5mvhKJaeKTO5bEzqymcltxLfjC8dNZFqgKrvrpXa2J"
