---
mthomson    :
    comment : "Mick Thomson"
    keys    :
      - key : "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCy/3WzzpMMJPOKqrkvFM4m5Wjrx6wTgag61P7yPXH3teTgNkf04C4dt9DG4imfleRb2w2o11Tw09EhiJ0eGtLdTi/WLzqT1+T+wCyXSEF+UKr/er1ZKQlJE3Y5cRX097jRKYmxrb9yEmIp1iOa0sk99mYSU92T4+OpfxOKgbzZv7YytonUCt0h6kpGkQ0cvRTaRz2flTskNce2qLXPTTlQ/IRjyP9tiTgtjn2QUryoHRmn4J/BmpbKy9BevdiV103iE/bcb24quyrI94hJQ2QQTh2laSEFP9je4q5jmkYEeMCX0WLomveUiyrtEMYAIvCq9ZZFz1SJ/6uXk8piqg2l"
